### ISSUE TITLE
【徵才】COBINHOOD 柯賓漢數位金融科技 Blockchain Researcher

### ISSUE THREAD

**Issue by richardcwyo** [EtherTW/jobs#12]
## Team Description/ Location
Cobinhood is a place for dreamers and doers. Cobinhood has vision to become the largest and most successful cryptocurrency exchange in the world.

You’ll work on the bleeding edge of blockchain technology, including Bitcoin, Ethereum and other cryptocurrencies, and play an important role in helping shape the future of how the world sees and uses money.

+ Location: Xinyi District, Taipei City

## Job Description
+ The work of blockchain researcher will involve the dissemination, internally and externally, of the results of such activities through publications, patents, seminars, and representing COBINHOOD at professional meetings, in professional societies and universities.
+ Provide techinial planning and support for initial blockchain product development

## Skills & Requirements
+ Passionate about cryptocurrency and blockchain
+ PhD in computer science related background with research record and commitment in one or more of the following areas:
  - distributed systems and large-scale web applications
  - performance modeling and analysis with focus on scalability
  - cryptography, including asymmetric (pub/priv key), symmetric, hash functions, encryption/signatures.
+ Familiar with Blockchain technology or other distributed system.
+ Understanding of the P2P networking
+ Understanding of the cryptographic principles
+ Understanding of various distributed consensus methodologies(Raft, Mining, PoS, Paxos, etc).

## Salary Range
Annual NTD84,000-NTD150,000 x 14
有討論空間

## Benefits
+ 公司近捷運象山, 101站
+ 彈性上下班，再也不用擠電梯擠車位了
+ 不打卡，不簽到
+ 休假制度優於勞基法：報到當日起即給與7天特休
+ 員工配股/員工認股
+ 每月點心櫃補到滿，想吃什麼自己點
+ 每位員工皆配備apple筆電
+ 彈性午休時間
+ 每週例行歡樂午餐時光，各種知名餐廳與美味餐點等著你
+ 豐厚獎金，肯拚就有收穫
+ 主管級員工椅及休息區，午睡時光讓你精力充沛

## Contact
cv/resume sent to careers@cobinhood.com

## Interview Process
HR/ Engineers/ CEO face to face interview

**Comment by changwu-tw** [comment]
原來 reseacrher 在這樣的公司薪資這麼低 Q_Q

**Comment by HuangJi** [comment]
QQ
