### ISSUE TITLE
【徵才US or TW】Smart Contract Developer (年薪百萬以上 TWD)

### ISSUE THREAD

**Issue by costabrent** [EtherTW/jobs#13]
// Recommended items to include. Items can be added or deleted freely.
// Tech stack is also recommended.
// delete above lines when done.

## Contact

# 中文版

// 以下是建議填寫項目，可自由增刪排序~
// 也建議標註團隊目前技術框架
// ^ 上面的看完就可以刪了~

## 聯絡方式costabrent@gmail.com

**Comment by ChihChengLiang** [comment]
抱歉，請問內容是否要重新整理編輯一下？

**Comment by costabrent** [comment]
Can you help?

On Wed, Nov 29, 2017 at 10:43 PM, Chih Cheng Liang <notifications@github.com

**Comment by ChihChengLiang** [comment]
comment 右上角應該有個筆的按鈕可以編輯

**Comment by ChihChengLiang** [comment]
年久失修
