### ISSUE TITLE
Status.im

### ISSUE THREAD

**Issue by changwu-tw** [EtherTW/jobs#3]
## Community Manager

TELECOMMUTE · Switzerland

### DESCRIPTION

[Status](https://status.im/) is growing our core team, and we're looking for both an English and Chinese Community Manager to join us part-time or full-time. You will play a major role in communicating our vision for what we're building at Status.

We already have a really wonderful group of people helping to support the project, and we're seeking someone with excellent public communication skills who cares deeply about Ethereum and decentralization.

A strong technical understanding of Status is preferred. You will be working alongside Tatu, Carl, Jarrad, and the rest of our development team.

### The role includes:

- Engaging with the developer community - helping to find DApps we can work with more closely, and help pointing new contributors to the right developer resources and answer questions.
- Writing articles, blog posts, and having meaningful discussion on Slack and social media about how we can improve Status, and more broadly bring Ethereum to a wider audience.
- Engaging with relevant communities outside of the crypto-sphere, to build awareness for Status - and taking the time to discover their needs, and understanding their feedback.
- Interviewing other great projects in the space, being interviewed in press and podcasts, presenting at meet-ups, and spreading the Status gospel.

We only hire people who are able to do a job better than we could do it ourselves, so the successful candidate will be overflowing with communication strategies for Status that they can begin applying right away.

You must be fluent in English or Chinese at a native speaker level, with outstanding verbal and written communication skills. We don’t mind where you live, our current team of 10 is scattered all over the world.

### Apply from:

1. [https://status-platform.workable.com/jobs/477781/candidates/new](https://status-platform.workable.com/jobs/477781/candidates/new)
2. Then join [http://slack.status.im](http://slack.status.im) and PM @ carl

**Comment by yaochunghu** [comment]
Opening has been closed

**Comment by ChihChengLiang** [comment]
Thanks for the Info @yaochunghu
