### ISSUE TITLE
【台北/Remote】Cartesi - Senior Software Engineer/Architect

### ISSUE THREAD

**Issue by colinsteil** [EtherTW/jobs#41]
**Senior Software Engineer/Architect**

Welcome to Cartesi. Cartesi is a decentralized and scalable linux infrastructure solving the problems of scalability and infrastructure for blockchains. Blockchain applications can now be built with all software available today while also being free from the limits and high costs of blockchains; still preserving their security guarantees and consensus. Cartesi brings real world computations to the blockchain.

We are an early stage project that is launching their tech with an energetic team located in both Taipei and Rio de Janeiro. We are looking to hire awesome people that will help ramp up our engineering department and achieve our vision of making the development and use of blockchain applications as close as possible to their centralized counterparts.

*Working with Cartesi is awesome, how about a few perks?*

- Flexible work hours and location (remote is no problem).
- Potential to be a big part of the project as it develops, own your work and contribute your visions and ideas.
- Work with an enthusiastic team that likes to have fun and really cares about what we’re building.
- Flexible annual leave/holidays.
- Plus more! Help build our culture.

*What will you do?*

Working as part of a small team, you’ll be in charge of a variety of complex tasks related to architecting, designing, developing, troubleshooting, debugging, and implementing software for the Cartesi infrastructure, potentially integrating it to different blockchains and using it to prototype decentralized applications. 

*We’re looking for somebody cool who knows their field! That might look like this!*

- Passion, drive and a desire to learn new things
- Theoretical understanding of blockchain tech
- 7+years of software development
- Fast learning
- Good communication skills
- Fluent English
- Understanding of how to design systems, conceive micro-services, API’s and protocols
- Ability to travel to client locations as needed

*Compensation*

75k - 200k NTD/month. We are looking for the best people that fit in our team. We are ready to pay a great salary to the right people!

*Interested?* 

We’d love to chat with you! Send us a message at info@cartesi.io with the job title as the subject along with a bit about yourself and why you love blockchain and are interested in what we’re building at Cartesi.

Learn more at https://cartesi.io and check out our social channels/videos!

**Comment by colinsteil** [comment]
Updated with salary info.

**Comment by ChihChengLiang** [comment]
Label removed 👍
