### ISSUE TITLE
[West Pharmaceutical Services]- Sr. Data Security Engineer/Blockchain Engineer

### ISSUE THREAD

**Issue by sc0Vu** [EtherTW/jobs#52]
## Team Description/ Location
Working at West means having an opportunity to work by the side of our patients and customers, our global team members and the communities in which we operate – which all help contribute to a Healthier World.

At West, we are by the side of patients. The work we do impacts patients’ lives each and every day – our products are a critical part of healthcare delivery and we are proud of the role we play to improve patient health. We work by the side of our team members. We come together as one global team to deliver for our customers and help them address their challenges. We are a diverse, close-knit community of professionals, where everyone has a voice and opportunity to learn and grow through mutual trust and respect. With a 95 year plus history, we have a track record for success, which includes reported sales of $2.14B in 2020. We serve by the side of our community. Giving back is in our DNA—our team members across more than 50 sites globally are involved with hundreds of charities that have special meaning to them through our West Without Borders team member-led giving program.

## Job Description
This role requires knowledge and expertise to participate in the development and maintenance of West IoT solutions with a targeted view toward system and data security. This role will work with an international team to bring the power of IoT in the Pharmaceutical space, contributing to a more efficient and effective production flow as well as instrumentally contribute to West Pharma IoT internal and customer facing capabilities.

### Essential Duties And Responsibilities

* Engineer products and services with international team for both internal and external stakeholders
* Build performant and reliable Internet-of-Things software components with various technologies
* Lead the design, development and improvement of IoT Systems Data security and integrity
* Propose secure and scalable architecture to power confidential data exchange
* Design & develop new features according to stakeholders’ requirements
* Collaborates with senior roles to complete projects from prototypes to production deployment
* Coach and evangelized data security best practices
* Trace code and understand the design of complex systems
* Take ownership of projects and deliverable
* Other duties as assigned

### Education And Experience

* Bachelor’s degree in Computer Science, Engineering, or equivalent preferred
* 4+ years of related work experience

### Knowledge, Skills And Abilities

* Ability to read/write/speak/listen in English
* Solid development experience with various programing languages & databases
* Proven block-chain technology knowledge and hands-on experience
* Strong web-security knowledge and hands-on experience
* Strong knowledge of communication encryption (TLS, PKI, Digital Signature)
* Experience in building distributed or data intensive systems
* Programing experience in Erlang/Elixir a plus
* Experience with Cloud (Azure) services and Container Orchestration systems (eg. K8s) a plus
* Ability to work autonomously in a fast-paced and complex environment with a self-motivated work ethic; use sound judgment with an ability to manage multiple priorities with a sense of urgency
* Demonstrated ability to exercise independent judgment in making decisions and resolving complex problems related to general and technical aspects of the job.
* Able to comply with the company’s safety and quality policies at all times

### Physical And Travel Requirements

* Less than 10% travel, including international and within Asia Pacific
* Occasional on-call work required
* Flexibility to work with teams in different time zones (incl. Evening meetings) 

## Salary Range
1.4M - 1.8M

## Benefits
TBD

## Contact

kimberley.eby@westpharma.com or 

apply on Linkedin: https://www.linkedin.com/jobs/view/2676120565/

**Comment by sauvainr** [comment]
Our new Taipei office has a great location right on the Nanging Fuxing station [https://goo.gl/maps/hC3txXmCdgu1vybS6](https://goo.gl/maps/hC3txXmCdgu1vybS6).

For any question on this position feel free to reach me at Renaud.Sauvain@westpharma.com.
