### ISSUE TITLE
資策會創研所區塊鏈計畫誠徵工程師

### ISSUE THREAD

**Issue by rekiwu** [EtherTW/jobs#7]
## 團隊簡介/地點
執行經濟部區塊鏈計畫，開發區塊鏈基礎建設相關系統與工具
台北市松山區 民生東路四段133號 2樓

## 團隊工作內容
研究Blockchain Technology
應用Blockchain Technology
發展Middleware及維護
開發Web及維護
產出技術文件

## 能力需求
JavaScript 或 Node.JS (es6/es7)
使用 Git、Redmine、Slack 等DevOps工具
基礎 shell script in Ubuntu/CentOS

基本 Word、Powerpoint等文書軟體技能
TOEIC450分以上 (面試時另有考試)

## 加分
Golang、Solidity、Container
Nginx、MongoDB、Redis、RabbitMQ等

Run過DLTDOJO所有範例
能定期參加Ethereum Meetup
對Blockchain，應用服務發展有興趣...

## 薪資範圍
需另送核薪 (五個工作天後告知)
參考：碩畢且工作滿三年，為副研究員級

## 工時/特休
週休二日，彈性工時
原則上09~18 (中午休息1hr)

## 福利/推薦項
三節禮品及禮金
語文及學位進修補助等等

## 聯絡方式
Reki  rekiwu@iii.org.tw

**Comment by rekiwu** [comment]
@

**Comment by rekiwu** [comment]
我找不到怎麼加Label...

**Comment by ChihChengLiang** [comment]
Label 手動加的 XD

**Comment by rekiwu** [comment]
原來如此 XD
