### ISSUE TITLE
資策會服創所 誠徵區塊鏈工讀生 [108年第一梯] 

### ISSUE THREAD

**Issue by rekiwu** [EtherTW/jobs#8]
## 團隊簡介/地點
資策會 數位服務創新研究所 區塊鏈xyz計畫
台北市松山區 民生東路四段133號 8樓

## 工作內容
協助Ethereum上的智能合約及Dapp研究
協助Hyperledger聯盟鏈測試研究
協助蒐集區塊鏈產業的中英文資料

## 能力需求
知道Solidity，ERC系列是什麼
能1分鐘內簡介 Ethereum及Hyperledger Fabric的差別
基本的 Word、Powerpoint等文書軟體技能
會使用 Git、Redmine、Slack 等開發協作工具

## 加分
不是初學者
看過過 [DLTDOJO範例](https://dltdojo.org/)
定期參加社群活動，例如:[Taipei Ethereum Meetup](https://www.meetup.com/Taipei-Ethereum-Meetup/)
對Blockchain的應用服務設計 (例如: Token Model) 有興趣...

## 薪資範圍
碩一：日薪 1,440 TWD
碩二：日薪 1,570 TWD
上列是2017的薪資(僅供參考)，現在基本薪資已調漲了，

## 工時
聘期最長一年
基本上班時間：0900~1800
每週總工時至少24小時，例如：0.5天 + 0.5天 + 2天
詳細可再面議

## 福利/推薦項
有資策會員工福利...

## 聯絡方式
Reki  
rekiwu@iii.org.tw

**Comment by kevinyin9** [comment]
所以現在是不是不招了 :(

**Comment by ChihChengLiang** [comment]
待 @rekiwu 回答囉。已結束的徵才可 close issue

**Comment by rekiwu** [comment]
不好意思，因名額數量有變，故已招滿了，
請管理員Closed。
之後若再有名額，我會再度開放。

**Comment by rekiwu** [comment]
@ChihChengLiang 早安，請問可以reopen嗎？

**Comment by rekiwu** [comment]
感恩
就是重新再徵工讀生囉

**Comment by rekiwu** [comment]
107年第一梯開徵啦~~

**Comment by rekiwu** [comment]
107年第三梯開徵中~~

**Comment by rekiwu** [comment]
107年工讀生已額滿
預徵108年工讀生，可於108年二月開始上班
歡迎大學碩一碩二生參加

**Comment by rekiwu** [comment]
updated
2019年第一梯工讀生徵人中
